name: Move Issue to WiP

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    name: Move Issue to WiP Column
    steps:
      - name: Move Issue to Column
        uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Java-Application
          column: Work in Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
