# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI mit Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: JDK 1.8 Setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Build
      run: mvn -B package --file pom.xml
